//! IPC contract codegen.
//!
//! `cargo run -p xtask -- generate-ipc` derives a deterministic TypeScript
//! definition of the Rust IPC projection types and writes it to
//! `shared/ipc.generated.ts` — alongside, never overwriting, the hand-authored
//! `shared/types.ts` domain model. The drift guard (`git diff --exit-code`)
//! then enforces that the committed file matches the Rust source of truth.

use std::path::PathBuf;

use medicolegaltemplate_lib::projection::{ClientViewModel, DocumentSummary, PIRSTableViewModel};
use medicolegaltemplate_lib::reducer::ClientState;
use medicolegaltemplate_lib::{EventHistoryItem, PersistConfirmation, VersionDiff};
use specta::Types;
use specta_typescript::Typescript;

// Numeric/JSON representation is handled by per-field `#[specta(type = ...)]`
// overrides on the Rust structs (u64/usize -> Number, serde_json::Value ->
// Unknown, DateTime -> String). `specta_serde::Format` applies serde semantics
// (e.g. `#[serde(rename_all)]`) so the generated TS matches runtime JSON.

fn main() {
    match std::env::args().nth(1).as_deref() {
        Some("generate-ipc") => generate_ipc(),
        other => {
            eprintln!("unknown xtask command: {other:?}\nusage: cargo run -p xtask -- generate-ipc");
            std::process::exit(2);
        }
    }
}

fn generate_ipc() {
    // Register the real IPC-boundary projection types. Fixed order ⇒ deterministic output.
    let types = Types::default()
        .register::<ClientViewModel>()
        .register::<DocumentSummary>()
        .register::<PIRSTableViewModel>()
        .register::<EventHistoryItem>()
        .register::<VersionDiff>()
        .register::<PersistConfirmation>()
        .register::<ClientState>();

    let body = Typescript::default()
        .export(&types, specta_serde::Format)
        .expect("specta TypeScript export failed");

    let header = "// @generated by `cargo run -p xtask -- generate-ipc` — DO NOT EDIT.\n\
                  // Source of truth: backend/src-tauri/src/projection.rs (Rust IPC types).\n\
                  // Hand-authored domain model lives in shared/types.ts and is never touched here.\n\n";

    let out = format!("{header}{}\n", body.trim_end());

    // CWD for `cargo run -p xtask` is the workspace root (backend/src-tauri);
    // the repo-root shared/ dir is two levels up.
    let path = PathBuf::from("../../shared/ipc.generated.ts");
    std::fs::write(&path, out).expect("failed to write shared/ipc.generated.ts");
    eprintln!("generate-ipc: wrote {}", path.display());

    emit_runtime_keys();
}

/// Sorted top-level JSON keys produced by real serde serialization of `v`.
fn serde_keys<T: serde::Serialize>(v: &T) -> Vec<String> {
    match serde_json::to_value(v).expect("serialize") {
        serde_json::Value::Object(m) => {
            let mut k: Vec<String> = m.keys().cloned().collect();
            k.sort();
            k
        }
        _ => vec![],
    }
}

/// Emit the actual serde field names (runtime contract) for each structured IPC
/// type, from real serialization of structural zero-instances (no fabricated
/// domain data). The contract test asserts these equal the generated TS fields.
fn emit_runtime_keys() {
    use chrono::{DateTime, Utc};
    use serde_json::Value;

    let epoch: DateTime<Utc> = DateTime::from_timestamp(0, 0).unwrap();
    let mut map: std::collections::BTreeMap<&str, Vec<String>> = Default::default();

    map.insert(
        "ClientViewModel",
        serde_keys(&ClientViewModel {
            id: String::new(),
            demographics: None,
            last_version: 0,
            created_at: None,
            updated_at: None,
            document_count: 0,
            documents: vec![],
            entities: vec![],
            timeline: vec![],
            pirs_snapshots: vec![],
        }),
    );
    map.insert("ClientState", serde_keys(&ClientState::default()));
    map.insert(
        "DocumentState",
        serde_keys(&medicolegaltemplate_lib::reducer::DocumentState {
            document_id: String::new(),
            file_name: String::new(),
            char_count: 0,
            method: String::new(),
            uploaded_at: epoch,
        }),
    );
    map.insert(
        "DocumentSummary",
        serde_keys(&DocumentSummary {
            id: String::new(),
            file_name: None,
            method: None,
            char_count: 0,
            uploaded_at: None,
        }),
    );
    map.insert(
        "EventHistoryItem",
        serde_keys(&EventHistoryItem {
            version: 0,
            timestamp: String::new(),
            event_type: String::new(),
        }),
    );
    map.insert(
        "VersionDiff",
        serde_keys(&VersionDiff {
            field: String::new(),
            from: Value::Null,
            to: Value::Null,
        }),
    );
    map.insert(
        "PersistConfirmation",
        serde_keys(&PersistConfirmation::default()),
    );
    map.insert(
        "PIRSTableViewModel",
        serde_keys(&PIRSTableViewModel {
            version: 0,
            snapshot: Value::Null,
            created_at: String::new(),
        }),
    );

    let json = serde_json::to_string_pretty(&map).expect("serialize keys");
    let dir = PathBuf::from("../../tests/contracts");
    std::fs::create_dir_all(&dir).expect("mkdir tests/contracts");
    let path = dir.join("ipc.runtime-keys.json");
    std::fs::write(&path, format!("{json}\n")).expect("write runtime-keys");
    eprintln!("generate-ipc: wrote {}", path.display());
}
