// @generated by `cargo run -p xtask -- generate-ipc` — DO NOT EDIT.
// Source of truth: backend/src-tauri/src/projection.rs (Rust IPC types).
// Hand-authored domain model lives in shared/types.ts and is never touched here.

// This file has been generated by Specta. Do not edit this file manually.
export type ClientState = {
	client_id: string,
	last_version: number,
	/**
	 *  Timestamp of the first event seen for this client. Used so rebuilds
	 *  produce a deterministic `created_at` on the projection.
	 */
	first_seen: string | null,
	last_updated: string | null,
	/**  Demographics JSON, opaque to the reducer. */
	demographics: unknown | null,
	documents: DocumentState[],
	/**
	 *  True once a `ClientDeleted` event has been observed. Projection
	 *  uses this to remove the row from the read model; rebuild uses it
	 *  to skip the upsert entirely so deleted clients don't reappear.
	 */
	deleted?: boolean,
};

/**
 *  Read-only view assembled from `projection.db`. Returned by
 *  `get_client_view`; never derived from events directly at read time.
 */
export type ClientViewModel = {
	id: string,
	/**
	 *  Full demographics JSON as stored on the projection. Parsed into a
	 *  `serde_json::Value` so every key round-trips losslessly.
	 */
	demographics: unknown | null,
	last_version: number,
	created_at: string | null,
	updated_at: string | null,
	document_count: number,
	documents: DocumentSummary[],
	/**  Placeholder — populated when entity extraction lands on the projection. */
	entities: unknown[],
	/**  Placeholder — populated when timeline reconstruction lands. */
	timeline: unknown[],
	/**  All PIRS snapshot rows for this client, ordered by version. */
	pirs_snapshots: PIRSTableViewModel[],
};

export type DocumentState = {
	document_id: string,
	file_name: string,
	char_count: number,
	method: string,
	uploaded_at: string,
};

export type DocumentSummary = {
	id: string,
	file_name: string | null,
	method: string | null,
	char_count: number,
	uploaded_at: string | null,
};

export type EventHistoryItem = {
	version: number,
	timestamp: string,
	event_type: string,
};

export type PIRSTableViewModel = {
	version: number,
	/**  Parsed snapshot JSON (whatever shape the producer wrote). */
	snapshot: unknown,
	created_at: string,
};

export type PersistConfirmation = {
	id: string,
	savedAt: string,
};

/**
 *  One field-level change between two snapshots. `from` and `to` are the
 *  raw `serde_json::Value`s — strings, numbers, nulls — left untouched so
 *  the consumer can render them however it wants.
 */
export type VersionDiff = {
	field: string,
	from: unknown,
	to: unknown,
};
